### ISSUE TITLE
Create study page

### ISSUE THREAD

**Issue by levibrooke** [project-l3j/flash#6]
This is the view that a user lands on after selecting a deck to study.

*Features*
- Shuffle deck ([Fisher-Yates Shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle)).
- User marks "yes" or "no" for if they got the card correct.

*Relevant user stories*
- As a user, I want to see a preloading quiz page, so that I can see a flashcard with a question displayed.

- As a user, on the quiz page I want to be able to click on the question, so that the card flips to see the answer.

- As a user, I want to see a back and next arrow button, so that I can see all cards through the deck.

- As a user, on the quiz page I want to have an option to review the entire deck of cards, so that I can go through the flashcards again.

- As a user, on completion of the quiz page, I want to have an option to review incorrect cards, so that I know what I can improve. 

- As a user, on completion of the quiz page, I want to navigate to the home page, so that I can go back to the home page.

**Comment by emd5** [comment]
Code is still in progress

**Comment by levibrooke** [comment]
This is good. Closing.
